[package]
name = "best-seeker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
thiserror = "2.0.18"
uuid = { version = "1.19.0", features = ["v4"] }

[dev-dependencies]
clippy = "0.0.302"
