services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: best-seeker-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  backend:
    build: .
    container_name: best-seeker-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      RUST_LOG: info
    ports:
      - "3000:3000"
    restart: on-failure

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: best-seeker-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - "3001:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    restart: on-failure

  email-worker:
    build:
      context: ./workers/email
      dockerfile: Dockerfile
    container_name: best-seeker-email-worker
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      RUST_LOG: info
    restart: on-failure

  test:
    build:
      context: .
      target: builder
    depends_on:
      - db
    environment:
      ENVIRONMENT: testing
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
