services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: best-seeker-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  garage:
    image: dxflrs/garage:v2.2.0
    container_name: best-seeker-garage
    restart: unless-stopped
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_ADMIN_TOKEN: ${GARAGE_ADMIN_TOKEN}
      GARAGE_METRICS_TOKEN: ${GARAGE_METRICS_TOKEN}
    ports:
      - "3900:3900" # S3 API
      - "3901:3901" # RPC
      - "3902:3902" # Web
      - "3903:3903" # Admin API
    volumes:
      - ./docker/garage/garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

  backend:
    build: .
    container_name: best-seeker-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      RUST_LOG: info
    ports:
      - "3000:3000"
    restart: on-failure

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: best-seeker-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - "3001:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    restart: on-failure

  email-worker:
    build:
      context: ./workers/email
      dockerfile: Dockerfile
    container_name: best-seeker-email-worker
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      RUST_LOG: info
    restart: on-failure

  scraper:
    build:
      context: ./workers/scraper
      dockerfile: Dockerfile
    container_name: best-seeker-scraper
    depends_on:
      - db
      - garage
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ENDPOINT_URL: http://garage:3900
      AWS_REGION: us-east-1
      S3_BUCKET_NAME: scraper
      LLM_SELECTED: ${LLM_SELECTED}
      GROQ_API_TOKEN: ${GROQ_API_TOKEN}
      GROQ_MODEL: ${GROQ_MODEL}
      RUST_LOG: info
    restart: on-failure

  test:
    build:
      context: .
      target: builder
    depends_on:
      - db
    environment:
      ENVIRONMENT: testing
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
  garage_meta:
  garage_data:
