name = "best-seeker"
manifest-path = "Cargo.toml"
exclude-files = [
    "src/main.rs",
    "src/shared/infrastructure/observability.rs",
    "src/shared/infrastructure/http/observability_middleware.rs",
    "src/shared/presentation/openapi.rs",
    "src/shared/db_sync.rs"
]
